name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Pipeline_MyNodeJSAPP  # Asegúrate de tener configurado este entorno
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        working-directory: ./backend/
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 44.203.90.191
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: '22'
          source: ./backend/
          target: /home/ec2-user/basicbackend/

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Restart PM2
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@44.203.90.191 'sudo pm2 restart nodejsapi'
