name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 44.203.90.191
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./backend/
          target: /home/ec2-user/your_app_directory/basicbackend/backend

      - name: Restart PM2
        run: ssh ec2-user@44.203.90.191 'sudo pm2 restart backend'
